#!/Users/henighan/miniconda3/envs/py375/bin/python
import sys
import av

path = sys.argv[1]
container = av.open(path)
# the stream frame count `container.streams.video[0].frames` is not reliable
# count the frames manually instead
nframes = 0
for _ in container.decode(video=0):
    nframes += 1
print(f"{nframes} frames")
