#!/bin/zsh                                                                                                   

if [ $TMUX ]
  then
    tmux detach-client
fi

SESSIONNAME="$(basename $1)"
tmux has-session -t=$SESSIONNAME &> /dev/null

if [ $? != 0 ] 
 then
    cd $1
    tmux new-session -s $SESSIONNAME -d
    tmux send-keys -t $SESSIONNAME "vim" C-m 
    tmux split-window
    tmux split-window -h
    tmux send-keys -t $SESSIONNAME -X cursor-left
    tmux select-pane -t 1
    tmux resize-pane -D 15
fi

tmux attach -t $SESSIONNAME
