#!/usr/local/bin/python3
import os
import sys
import argparse

parser = argparse.ArgumentParser(description="transformer params")
parser.add_argument("-m_div", help="m divisor", type=float)
parser.add_argument("-m_mlp", help="m divisor", type=float)
parser.add_argument("-m_attn", help="m divisor", type=float)
parser.add_argument("-ar", help="aspect ratio, d_mode/n_layer", type=float)
parser.add_argument("-params", help="target parameter count", type=float)
args = parser.parse_args()
beta = 2*(args.m_mlp + 2*args.m_attn)
n_layer = (args.params/beta/args.ar**2)**(1/3)
d_model = (args.ar*args.params/beta)**(1/3)
print(f"n_layer {n_layer} d_model {d_model}")
